[package]
name = "fasthash"
version = "0.4.1"
authors = ["Flier Lu <flier.lu@gmail.com>"]
description = "A suite of non-cryptographic hash functions for Rust."
homepage = "https://github.com/flier/rust-fasthash"
repository = "https://github.com/flier/rust-fasthash.git"
documentation = "https://flier.github.io/rust-fasthash/"
keywords = ["hash", "hashing"]
license = "Apache-2.0"
edition = "2018"

[features]
default = ["doc", "native"]
doc = []
native = ["fasthash-sys/native"]
aes = ["fasthash-sys/aes"]
sse41 = ["fasthash-sys/sse41"]
sse42 = ["fasthash-sys/sse42"]
avx = ["fasthash-sys/avx"]
avx2 = ["fasthash-sys/avx2"]
gen = ["fasthash-sys/gen"]

[dependencies]
cfg-if = "0.1"
lazy_static = "1.3"
num-traits = "0.2"
xoroshiro128 = "0.3"
seahash = "3.0"
digest = { version = "0.8", optional = true }

fasthash-sys = { version = "0.4", path = "../fasthash-sys" }

[dev-dependencies]
criterion = "0.3"

[target.'cfg(any(target_arch = "x86", target_arch = "x86_64"))'.build-dependencies]
raw-cpuid = "7"

[[bench]]
name = "hash"
harness = false
